# Generated by Django 4.2.2 on 2023-06-06 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                (
                    "created",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 6, 6, 4, 50, 36, 926356, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="Genral",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task.category",
                    ),
                ),
            ],
        ),
    ]
